-- ViceHub X — Collection wallpapers (30 nouveaux + thèmes) — généré par scripts/gen-wallpapers.php
INSERT INTO products (name, slug, description, category, subcategory, price, currency, image, sale_type, digital_file, merchant, badge, featured, sort, lang) VALUES
('Cabriolet Rose — Vice Boulevard','wallpaper-car-pink-vice','Un cabriolet rose vif sur un boulevard bordé de palmiers au coucher de soleil. L’essence de Vice City.','wallpaper','voiture',5.00,'EUR','/preview.php?p=wp-car-pink-vice','stripe','storage/wallpapers/wp-car-pink-vice.png','ViceHub Store','HD',1,300,'fr'),
('Supercar Néon — Downtown','wallpaper-car-supercar-night','Une supercar fend la nuit du centre-ville, reflets magenta et cyan sur l’asphalte mouillé.','wallpaper','voiture',5.00,'EUR','/preview.php?p=wp-car-supercar-night','stripe','storage/wallpapers/wp-car-supercar-night.png','ViceHub Store','HD',0,301,'fr'),
('Muscle Car — Front de Mer','wallpaper-car-muscle-beach','Une muscle car américaine longe l’océan turquoise sous une lumière dorée. Pur style rétro.','wallpaper','voiture',5.00,'EUR','/preview.php?p=wp-car-muscle-beach','stripe','storage/wallpapers/wp-car-muscle-beach.png','ViceHub Store','HD',0,302,'fr'),
('Lowrider Chromé — Néon','wallpaper-car-lowrider','Un lowrider rutilant glisse dans une rue néon, chromes étincelants et ambiance eighties.','wallpaper','voiture',5.00,'EUR','/preview.php?p=wp-car-lowrider','stripe','storage/wallpapers/wp-car-lowrider.png','ViceHub Store','HD',0,303,'fr'),
('Tout-Terrain — Everglades','wallpaper-car-offroad-glades','Un pick-up tout-terrain éclabousse les marais au lever du soleil. Aventure dans les Everglades.','wallpaper','voiture',5.00,'EUR','/preview.php?p=wp-car-offroad-glades','stripe','storage/wallpapers/wp-car-offroad-glades.png','ViceHub Store','HD',0,304,'fr'),
('Cabriolet Vintage — Ocean Drive','wallpaper-car-classic-deco','Un cabriolet d’époque garé devant les hôtels art déco illuminés de néons. Nuit sur Ocean Drive.','wallpaper','voiture',5.00,'EUR','/preview.php?p=wp-car-classic-deco','stripe','storage/wallpapers/wp-car-classic-deco.png','ViceHub Store','HD',0,305,'fr'),
('Hydravion — Décollage Doré','wallpaper-plane-seaplane','Un hydravion décolle d’une eau turquoise face à la skyline néon, au soleil couchant.','wallpaper','avion',5.00,'EUR','/preview.php?p=wp-plane-seaplane','stripe','storage/wallpapers/wp-plane-seaplane.png','ViceHub Store','HD',1,306,'fr'),
('Jet Privé — Skyline','wallpaper-plane-jet-skyline','Un jet privé survole la ville illuminée au crépuscule. Luxe et altitude.','wallpaper','avion',5.00,'EUR','/preview.php?p=wp-plane-jet-skyline','stripe','storage/wallpapers/wp-plane-jet-skyline.png','ViceHub Store','HD',0,307,'fr'),
('Biplan — Plage Ensoleillée','wallpaper-plane-biplane','Un biplan vintage survole une plage de palmiers sous un ciel bleu éclatant.','wallpaper','avion',5.00,'EUR','/preview.php?p=wp-plane-biplane','stripe','storage/wallpapers/wp-plane-biplane.png','ViceHub Store','HD',0,308,'fr'),
('Chasseur — Orage Tropical','wallpaper-plane-fighter-storm','Un chasseur traverse des nuages d’orage spectaculaires au-dessus de la côte. Tension maximale.','wallpaper','avion',5.00,'EUR','/preview.php?p=wp-plane-fighter-storm','stripe','storage/wallpapers/wp-plane-fighter-storm.png','ViceHub Store','HD',0,309,'fr'),
('Hélico — Survol Néon','wallpaper-plane-heli-city','Un hélicoptère survole la skyline néon de nuit, projecteur allumé. Ambiance polar.','wallpaper','avion',5.00,'EUR','/preview.php?p=wp-plane-heli-city','stripe','storage/wallpapers/wp-plane-heli-city.png','ViceHub Store','HD',0,310,'fr'),
('Vue Aérienne — Métropole','wallpaper-city-aerial-day','Vue aérienne grandiose d’une métropole côtière tropicale à l’heure dorée. Plages et gratte-ciels.','wallpaper','ville',5.00,'EUR','/preview.php?p=wp-city-aerial-day','stripe','storage/wallpapers/wp-city-aerial-day.png','ViceHub Store','HD',0,311,'fr'),
('Downtown — Heure Bleue','wallpaper-city-downtown-dusk','Les gratte-ciels du centre reflètent un ciel violet et orangé à l’heure bleue.','wallpaper','ville',5.00,'EUR','/preview.php?p=wp-city-downtown-dusk','stripe','storage/wallpapers/wp-city-downtown-dusk.png','ViceHub Store','HD',0,312,'fr'),
('Quartier des Canaux','wallpaper-city-canal-district','Un quartier de canaux aux façades art déco pastel, palmiers et petits bateaux. Douceur de vivre.','wallpaper','ville',5.00,'EUR','/preview.php?p=wp-city-canal-district','stripe','storage/wallpapers/wp-city-canal-district.png','ViceHub Store','HD',0,313,'fr'),
('Skyline sur l’Eau','wallpaper-city-skyline-water','La skyline néon se reflète sur une baie calme, rose et cyan. Carte postale de Vice City.','wallpaper','ville',5.00,'EUR','/preview.php?p=wp-city-skyline-water','stripe','storage/wallpapers/wp-city-skyline-water.png','ViceHub Store','HD',1,314,'fr'),
('Pont au Coucher de Soleil','wallpaper-city-bridge-sunset','Un long pont suspendu mène à la ville illuminée, lumières chaudes et reflets sur l’eau.','wallpaper','ville',5.00,'EUR','/preview.php?p=wp-city-bridge-sunset','stripe','storage/wallpapers/wp-city-bridge-sunset.png','ViceHub Store','HD',0,315,'fr'),
('Marché de Rue Latino','wallpaper-city-market-street','Un marché de rue latino animé au crépuscule, guirlandes lumineuses et étals colorés.','wallpaper','ville',5.00,'EUR','/preview.php?p=wp-city-market-street','stripe','storage/wallpapers/wp-city-market-street.png','ViceHub Store','HD',0,316,'fr'),
('Strip Néon — Casino','wallpaper-night-neon-strip','Le strip des casinos s’embrase de néons, enseignes éclatantes et voitures de luxe.','wallpaper','nuit',5.00,'EUR','/preview.php?p=wp-night-neon-strip','stripe','storage/wallpapers/wp-night-neon-strip.png','ViceHub Store','HD',0,317,'fr'),
('Piscine sur le Toit','wallpaper-night-rooftop-pool','Une piscine à débordement sur un toit, skyline en fond et lueur néon. Glamour absolu.','wallpaper','nuit',5.00,'EUR','/preview.php?p=wp-night-rooftop-pool','stripe','storage/wallpapers/wp-night-rooftop-pool.png','ViceHub Store','HD',1,318,'fr'),
('Rue sous la Pluie','wallpaper-night-rain-street','Une rue néon sous la pluie, reflets vifs sur l’asphalte. Atmosphère cinématographique.','wallpaper','nuit',5.00,'EUR','/preview.php?p=wp-night-rain-street','stripe','storage/wallpapers/wp-night-rain-street.png','ViceHub Store','HD',0,319,'fr'),
('Ruelle des Clubs','wallpaper-night-club-alley','Une ruelle de clubs vibrante d’enseignes néon et de foule. L’énergie de la nuit.','wallpaper','nuit',5.00,'EUR','/preview.php?p=wp-night-club-alley','stripe','storage/wallpapers/wp-night-club-alley.png','ViceHub Store','HD',0,320,'fr'),
('Jetée Illuminée','wallpaper-night-pier-lights','Une jetée et sa grande roue illuminées au bord de l’océan. Fête et lumières.','wallpaper','nuit',5.00,'EUR','/preview.php?p=wp-night-pier-lights','stripe','storage/wallpapers/wp-night-pier-lights.png','ViceHub Store','HD',0,321,'fr'),
('Skyline sous l’Orage','wallpaper-night-skyline-storm','La skyline de nuit sous un orage spectaculaire, éclairs au-dessus des tours.','wallpaper','nuit',5.00,'EUR','/preview.php?p=wp-night-skyline-storm','stripe','storage/wallpapers/wp-night-skyline-storm.png','ViceHub Store','HD',0,322,'fr'),
('Au Volant du Cabriolet','wallpaper-girl-convertible','Une jeune femme stylée en mode 80s conduit un cabriolet rose au coucher de soleil.','wallpaper','fille',5.00,'EUR','/preview.php?p=wp-girl-convertible','stripe','storage/wallpapers/wp-girl-convertible.png','ViceHub Store','HD',1,323,'fr'),
('Silhouette sur la Plage','wallpaper-girl-beach-sunset','Une silhouette élégante marche sur une plage de palmiers au soleil couchant.','wallpaper','fille',5.00,'EUR','/preview.php?p=wp-girl-beach-sunset','stripe','storage/wallpapers/wp-girl-beach-sunset.png','ViceHub Store','HD',0,324,'fr'),
('Portrait Néon','wallpaper-girl-neon-portrait','Un portrait artistique baigné de néons rose et cyan. Esthétique rétro eighties.','wallpaper','fille',5.00,'EUR','/preview.php?p=wp-girl-neon-portrait','stripe','storage/wallpapers/wp-girl-neon-portrait.png','ViceHub Store','HD',0,325,'fr'),
('Sur le Toit, Face à la Ville','wallpaper-girl-rooftop','Une femme assurée sur un toit domine la skyline néon de nuit.','wallpaper','fille',5.00,'EUR','/preview.php?p=wp-girl-rooftop','stripe','storage/wallpapers/wp-girl-rooftop.png','ViceHub Store','HD',0,326,'fr'),
('Au Bord de la Piscine','wallpaper-girl-poolside','Ambiance resort de luxe au bord de la piscine, palmiers et heure dorée.','wallpaper','fille',5.00,'EUR','/preview.php?p=wp-girl-poolside','stripe','storage/wallpapers/wp-girl-poolside.png','ViceHub Store','HD',0,327,'fr'),
('L’Esprit Biker','wallpaper-girl-biker','Veste en cuir et moto dans une rue néon. Attitude rétro et caractère.','wallpaper','fille',5.00,'EUR','/preview.php?p=wp-girl-biker','stripe','storage/wallpapers/wp-girl-biker.png','ViceHub Store','HD',0,328,'fr'),
('Élégance à la Marina','wallpaper-girl-marina','Sur un yacht à la marina ensoleillée, eaux turquoise et palmiers. Douceur estivale.','wallpaper','fille',5.00,'EUR','/preview.php?p=wp-girl-marina','stripe','storage/wallpapers/wp-girl-marina.png','ViceHub Store','HD',0,329,'fr');

-- Sous-thèmes des wallpapers déjà en boutique
UPDATE products SET subcategory='voiture' WHERE digital_file IN ('storage/wallpapers/wall-supercar.png','storage/wallpapers/wp-pink-cruiser.png','storage/wallpapers/wp-speedboat.png','storage/wallpapers/wp-muscle-diner.png','storage/wallpapers/wp-airboat.png','storage/wallpapers/wp-desert-road.png');
UPDATE products SET subcategory='avion' WHERE digital_file IN ('storage/wallpapers/wp-heli-night.png');
UPDATE products SET subcategory='ville' WHERE digital_file IN ('storage/wallpapers/wall-skyline.png','storage/wallpapers/wall-beach.png','storage/wallpapers/wall-aerial.png','storage/wallpapers/wall-marina.png','storage/wallpapers/wp-aerial-sunset.png','storage/wallpapers/wp-downtown-blue.png','storage/wallpapers/wp-marina-dusk.png','storage/wallpapers/wp-ocean-drive.png','storage/wallpapers/wp-storm-bay.png','storage/wallpapers/wp-street-market.png','storage/wallpapers/wp-beach-sunset.png','storage/wallpapers/wp-bridge.png');
UPDATE products SET subcategory='nuit' WHERE digital_file IN ('storage/wallpapers/wall-synthwave.png','storage/wallpapers/wall-nightlife.png','storage/wallpapers/wall-flamingo.png','storage/wallpapers/wp-rain-street.png','storage/wallpapers/wp-synthwave.png','storage/wallpapers/wp-club-alley.png','storage/wallpapers/wp-casino.png','storage/wallpapers/wp-pool-party.png','storage/wallpapers/wp-flamingo.png');
