
-- ====== Forum GTA VI : 50 personas de plus + catégorie + sujets ======
INSERT INTO users (username, email, display_name, password_hash, role) VALUES
('precommande_dan','precommande_dan@fans.vicehubx.test','PrecommandeDan','!','member'),
('deal_hunter_d','deal_hunter_d@fans.vicehubx.test','DealHunterD','!','member'),
('ps5_pierre','ps5_pierre@fans.vicehubx.test','PS5Pierre','!','member'),
('xbox_xavier','xbox_xavier@fans.vicehubx.test','XboxXavier','!','member'),
('collector_maniac','collector_maniac@fans.vicehubx.test','CollectorManiac','!','member'),
('day_one_dia','day_one_dia@fans.vicehubx.test','DayOneDia','!','member'),
('patient_paul','patient_paul@fans.vicehubx.test','PatientPaul','!','member'),
('wallet_warrior','wallet_warrior@fans.vicehubx.test','WalletWarrior','!','member'),
('trailer_addict','trailer_addict@fans.vicehubx.test','TrailerAddict','!','member'),
('florida_man','florida_man@fans.vicehubx.test','FloridaMan','!','member'),
('coop_dreamer','coop_dreamer@fans.vicehubx.test','CoopDreamer','!','member'),
('online_oga','online_oga@fans.vicehubx.test','OnlineOga','!','member'),
('lore_lucie','lore_lucie@fans.vicehubx.test','LoreLucie','!','member'),
('skeptik_sam','skeptik_sam@fans.vicehubx.test','SkeptikSam','!','member'),
('modder_mika','modder_mika@fans.vicehubx.test','ModderMika','!','member'),
('casual_clo','casual_clo@fans.vicehubx.test','CasualClo','!','member'),
('tryhard_tom','tryhard_tom@fans.vicehubx.test','TryhardTom','!','member'),
('story_first','story_first@fans.vicehubx.test','StoryFirst','!','member'),
('radio_raph','radio_raph@fans.vicehubx.test','RadioRaph','!','member'),
('screenshot_sky','screenshot_sky@fans.vicehubx.test','ScreenshotSky','!','member'),
('econ_emma','econ_emma@fans.vicehubx.test','EconEmma','!','member'),
('nostalgia_ned','nostalgia_ned@fans.vicehubx.test','NostalgiaNed','!','member'),
('hype_helena','hype_helena@fans.vicehubx.test','HypeHelena','!','member'),
('quiet_quentin','quiet_quentin@fans.vicehubx.test','QuietQuentin','!','member'),
('tech_tina','tech_tina@fans.vicehubx.test','TechTina','!','member'),
('biker_bob','biker_bob@fans.vicehubx.test','BikerBob','!','member'),
('heist_hugo','heist_hugo@fans.vicehubx.test','HeistHugo','!','member'),
('flamingo_fan','flamingo_fan@fans.vicehubx.test','FlamingoFan','!','member'),
('soundtrack_su','soundtrack_su@fans.vicehubx.test','SoundtrackSu','!','member'),
('veteran_vic','veteran_vic@fans.vicehubx.test','VeteranVic','!','member'),
('meme_maya','meme_maya@fans.vicehubx.test','MemeMaya','!','member'),
('completionist_cy','completionist_cy@fans.vicehubx.test','CompletionistCy','!','member'),
('rp_roman','rp_roman@fans.vicehubx.test','RPRoman','!','member'),
('street_racer','street_racer@fans.vicehubx.test','StreetRacer','!','member'),
('storm_chaser_s','storm_chaser_s@fans.vicehubx.test','StormChaserS','!','member'),
('budget_collector','budget_collector@fans.vicehubx.test','BudgetCollector','!','member'),
('console_war_no','console_war_no@fans.vicehubx.test','ConsoleWarNo','!','member'),
('early_bird','early_bird@fans.vicehubx.test','EarlyBird','!','member'),
('lurker_leo','lurker_leo@fans.vicehubx.test','LurkerLeo','!','member'),
('fan_art_fay','fan_art_fay@fans.vicehubx.test','FanArtFay','!','member'),
('pessimist_pat','pessimist_pat@fans.vicehubx.test','PessimistPat','!','member'),
('optimist_oli','optimist_oli@fans.vicehubx.test','OptimistOli','!','member'),
('data_miner','data_miner@fans.vicehubx.test','DataMiner','!','member'),
('couch_coop','couch_coop@fans.vicehubx.test','CouchCoop','!','member'),
('night_owl_n','night_owl_n@fans.vicehubx.test','NightOwlN','!','member'),
('first_gta','first_gta@fans.vicehubx.test','FirstGTA','!','member'),
('veteran_vera','veteran_vera@fans.vicehubx.test','VeteranVera','!','member'),
('region_ana','region_ana@fans.vicehubx.test','RegionAna','!','member'),
('hardcore_h','hardcore_h@fans.vicehubx.test','HardcoreH','!','member'),
('chill_charles','chill_charles@fans.vicehubx.test','ChillCharles','!','member');

INSERT INTO forum_categories (id, name, slug, description, icon, sort) VALUES
(6, 'GTA VI', 'gta-vi', 'Précommandes, éditions, hype et compte à rebours : tout sur GTA VI.', '🎮', 5);

INSERT INTO forum_threads (id, category_id, user_id, title, slug, pinned, created_at, last_post_at) VALUES
(14,6,53,'🎉 LES PRÉCOMMANDES DE GTA VI SONT OUVERTES !!','les-pr-commandes-de-gta-vi-sont-ouvertes-3f6',1, NOW() - INTERVAL 114 HOUR, NOW() - INTERVAL 108 HOUR),
(15,6,4,'Standard ou Ultimate, vous prenez quoi ?','standard-ou-ultimate-vous-prenez-quoi-3f7',0, NOW() - INTERVAL 106 HOUR, NOW() - INTERVAL 101 HOUR),
(16,6,53,'J’ai pris l’Ultimate Edition, posez-moi vos questions 😎','j-ai-pris-l-ultimate-edition-posez-moi-vos-questions-3f8',0, NOW() - INTERVAL 98 HOUR, NOW() - INTERVAL 93 HOUR),
(17,6,55,'Précommande PS5 ou Xbox ? (et le mois de GTA+ offert 👀)','precommande-ps5-ou-xbox-et-le-mois-de-gta-offert-3f9',0, NOW() - INTERVAL 90 HOUR, NOW() - INTERVAL 85 HOUR),
(18,6,54,'Où précommander au meilleur prix ? (79,99 $ / 99,99 $)','ou-precommander-au-meilleur-prix-79-99-99-99-3fa',0, NOW() - INTERVAL 82 HOUR, NOW() - INTERVAL 77 HOUR),
(19,6,67,'Faut-il vraiment précommander ? Le débat 🍿','faut-il-vraiment-precommander-le-debat-3fb',0, NOW() - INTERVAL 74 HOUR, NOW() - INTERVAL 69 HOUR),
(20,6,14,'J-XXX : c’est quoi VOTRE plan pour le jour de la sortie ?','j-xxx-c-est-quoi-votre-plan-pour-le-jour-de-la-sortie-3fc',0, NOW() - INTERVAL 66 HOUR, NOW() - INTERVAL 61 HOUR),
(21,6,75,'Le Vintage Vice City Pack 🌴 (nostalgie ON)','le-vintage-vice-city-pack-nostalgie-on-3fd',0, NOW() - INTERVAL 58 HOUR, NOW() - INTERVAL 53 HOUR),
(22,6,94,'Pas de Collector physique cette fois… déçus ou pas ?','pas-de-collector-physique-cette-fois-decus-ou-pas-3fe',0, NOW() - INTERVAL 50 HOUR, NOW() - INTERVAL 45 HOUR),
(23,6,21,'Première fois que je précommande un jeu… des conseils ?','premiere-fois-que-je-precommande-un-jeu-des-conseils-3ff',0, NOW() - INTERVAL 42 HOUR, NOW() - INTERVAL 37 HOUR),
(24,6,4,'L’Ultimate à 99,99 $ : ça vaut les 20 $ de plus ?','l-ultimate-a-99-99-ca-vaut-les-20-de-plus-400',0, NOW() - INTERVAL 34 HOUR, NOW() - INTERVAL 29 HOUR),
(25,6,59,'On se fait une soirée de lancement ViceHub X ? 🌴','on-se-fait-une-soiree-de-lancement-vicehub-x-401',0, NOW() - INTERVAL 26 HOUR, NOW() - INTERVAL 21 HOUR),
(26,6,60,'Team patience vs team day-one : qui a raison ? 😅','team-patience-vs-team-day-one-qui-a-raison-402',0, NOW() - INTERVAL 18 HOUR, NOW() - INTERVAL 13 HOUR),
(27,6,65,'GTA+ offert : vous comptez l’utiliser pour le online ?','gta-offert-vous-comptez-l-utiliser-pour-le-online-403',0, NOW() - INTERVAL 10 HOUR, NOW() - INTERVAL 5 HOUR);

INSERT INTO forum_posts (thread_id, user_id, body, created_at) VALUES
(14,53,'ÇA Y EST LES AMIS, les précommandes sont LÀ 😭🌴 j’ai pris l’Ultimate direct, mon cœur n’a pas tenu une seconde !', NOW() - INTERVAL 6840 MINUTE),
(14,75,'Enfin… j’attends ça depuis 2002. Et le Vintage Vice City Pack en bonus, j’en ai la larme à l’œil 🥲', NOW() - INTERVAL 6811 MINUTE),
(14,59,'DAY ONE confirmé, congé posé pour le 19 novembre 😎', NOW() - INTERVAL 6782 MINUTE),
(14,9,'Standard ou Ultimate, la vraie question… 79,99 $ vs 99,99 $, faut que je réfléchisse 🏎️', NOW() - INTERVAL 6753 MINUTE),
(14,98,'Précommande validée à la première minute, fier de mon numéro de commande 🔥', NOW() - INTERVAL 6724 MINUTE),
(14,10,'Rappel utile : le Vintage Vice City Pack est réservé aux achats NUMÉRIQUES avant le 20 novembre. Lisez bien 👀', NOW() - INTERVAL 6695 MINUTE),
(15,4,'Du coup il n’y a que deux éditions : Standard à 79,99 $ et Ultimate à 99,99 $. Vous partez sur quoi ?', NOW() - INTERVAL 6360 MINUTE),
(15,57,'Ultimate sans hésiter. 5 véhicules exclusifs, des boutiques en plus, une mission annexe… 20 $ de plus, ça les vaut.', NOW() - INTERVAL 6331 MINUTE),
(15,65,'Standard pour moi, je veux d’abord l’histoire. Je verrai pour le reste plus tard.', NOW() - INTERVAL 6302 MINUTE),
(15,85,'L’Ultimate distribue ses contenus tout au long de l’aventure, c’est ça qui me tente le plus.', NOW() - INTERVAL 6273 MINUTE),
(15,92,'Je lis tout avant de décider, mais l’Ultimate me fait de l’œil aussi.', NOW() - INTERVAL 6244 MINUTE),
(16,53,'Voilà c’est fait, Ultimate validée ! AMA sur ce qu’elle contient.', NOW() - INTERVAL 5880 MINUTE),
(16,88,'Elle contient quoi exactement de plus que la Standard ?', NOW() - INTERVAL 5851 MINUTE),
(16,53,'5 véhicules exclusifs, 4 variantes d’armes, des packs cosmétiques, 5 boutiques (Rideout Customs, Electric Fang Tattoo…), un garage dédié et une mission annexe en plus 🔥', NOW() - INTERVAL 5822 MINUTE),
(16,43,'Et niveau online ? j’espère pas que ça déséquilibre tout.', NOW() - INTERVAL 5793 MINUTE),
(16,53,'Là-dessus on verra à la sortie, mais c’est surtout du contenu solo réparti dans l’histoire.', NOW() - INTERVAL 5764 MINUTE),
(17,55,'Team PlayStation ici. Et le mois de GTA+ offert en précommande numérique, ça compte pas pour rien !', NOW() - INTERVAL 5400 MINUTE),
(17,56,'Pareil côté Xbox, GTA+ offert aussi sur le Microsoft Store. GTA$ 500 000 d’entrée, je dis pas non.', NOW() - INTERVAL 5371 MINUTE),
(17,89,'Vous allez pas recommencer la console-war 😅 le GTA+ marche sur les deux stores, soyez zen.', NOW() - INTERVAL 5342 MINUTE),
(17,16,'Moi c’est surtout les Shark Cards +15 % et la bibliothèque GTA+ qui m’intéressent.', NOW() - INTERVAL 5313 MINUTE),
(17,17,'Team PC qui attend dans le silence… patience, notre heure viendra 🕯️', NOW() - INTERVAL 5284 MINUTE),
(18,54,'Je compare tout depuis ce matin. Standard 79,99 $, Ultimate 99,99 $, à voir selon les revendeurs.', NOW() - INTERVAL 4920 MINUTE),
(18,88,'Pense aux versions régionales, mais attention aux restrictions d’activation.', NOW() - INTERVAL 4891 MINUTE),
(18,100,'Si tu prends en boîte, c’est seulement la Standard (code in box). L’Ultimate est numérique only.', NOW() - INTERVAL 4862 MINUTE),
(18,60,'Perso j’attends un poil, mais le Vintage Vice City Pack expire le 20 novembre, faut pas trop traîner.', NOW() - INTERVAL 4833 MINUTE),
(18,53,'Voilà, c’est ça le piège : le bonus est limité dans le temps 👀', NOW() - INTERVAL 4804 MINUTE),
(19,67,'Précommander un jeu pas sorti, c’est risqué non ? « wait and see ».', NOW() - INTERVAL 4440 MINUTE),
(19,60,'D’accord en général, mais là le Vintage Vice City Pack est réservé à la précommande numérique. Ça change la donne.', NOW() - INTERVAL 4411 MINUTE),
(19,53,'Exactement. Si tu joues day-one et que le pack te parle, autant en profiter.', NOW() - INTERVAL 4382 MINUTE),
(19,95,'C’est Rockstar, confiance totale sur la qualité. Je fonce 🤩', NOW() - INTERVAL 4353 MINUTE),
(19,43,'Confiance oui, mais je reste vigilant sur l’économie online, comme toujours.', NOW() - INTERVAL 4324 MINUTE),
(20,14,'CONGÉ POSÉ pour le 19 novembre. Frigo plein. Téléphone en avion. JE NE RÉPONDS À PERSONNE 😤🌴', NOW() - INTERVAL 3960 MINUTE),
(20,59,'Soirée de lancement avec les potes, on lance tous à minuit.', NOW() - INTERVAL 3931 MINUTE),
(20,69,'Moi je vais juste me balader tranquille la première heure, profiter de la ville 🌅', NOW() - INTERVAL 3902 MINUTE),
(20,21,'Mon tout premier GTA day one, je sais même pas par quoi commencer haha.', NOW() - INTERVAL 3873 MINUTE),
(20,102,'Conseil de vétéran : savoure l’intro, te précipite pas. Vice City se mérite.', NOW() - INTERVAL 3844 MINUTE),
(21,75,'Un clin d’œil à Vice City 2002 en bonus de précommande : véhicule + garage + cosmétiques pour Jason et Lucia. Je suis ÉMU.', NOW() - INTERVAL 3480 MINUTE),
(21,83,'Ça boucle la boucle. De 2002 à 2026, même ville, même magie. Respect Rockstar.', NOW() - INTERVAL 3451 MINUTE),
(21,81,'Hâte de voir le style des cosmétiques, j’espère du flashy 80s 🦩.', NOW() - INTERVAL 3422 MINUTE),
(21,62,'Petit rappel : pack inclus dans tout achat numérique AVANT le 20 novembre 2026. Notez la date.', NOW() - INTERVAL 3393 MINUTE),
(21,43,'Sympa le geste, tant que ça reste cosmétique et pas un avantage online.', NOW() - INTERVAL 3364 MINUTE),
(22,94,'Du coup pas de steelbook ni de statuette officielle, juste Standard et Ultimate numériques (et la Standard en boîte). Vous en pensez quoi ?', NOW() - INTERVAL 3000 MINUTE),
(22,57,'Un peu déçu en tant que collectionneur, j’aurais pris une statuette Jason & Lucia direct.', NOW() - INTERVAL 2971 MINUTE),
(22,65,'Moi ça m’arrange, je joue full numérique. Moins d’étagères à remplir 😅', NOW() - INTERVAL 2942 MINUTE),
(22,85,'L’essentiel c’est le jeu. Le contenu de l’Ultimate me suffit largement.', NOW() - INTERVAL 2913 MINUTE),
(22,53,'On peut toujours se faire plaisir avec des goodies fan (genre la boutique ici 👀🌴).', NOW() - INTERVAL 2884 MINUTE),
(23,21,'Je débute, GTA VI sera mon premier GTA ET ma première précommande. Aidez-moi 🙏', NOW() - INTERVAL 2520 MINUTE),
(23,60,'Garde ta preuve d’achat, vérifie la date de débit et la politique de remboursement.', NOW() - INTERVAL 2491 MINUTE),
(23,53,'Choisis bien Standard ou Ultimate, et numérique si tu veux le Vintage Vice City Pack. Bienvenue dans la hype 😄', NOW() - INTERVAL 2462 MINUTE),
(23,76,'BIENVENUE 🌴✨ tu vas A-DO-RER, prépare-toi à ne plus dormir.', NOW() - INTERVAL 2433 MINUTE),
(23,92,'Pose toutes tes questions ici, la communauté est top pour ça.', NOW() - INTERVAL 2404 MINUTE),
(24,4,'Je pèse le pour et le contre. 5 véhicules, 4 variantes d’armes, 5 boutiques, un garage et une mission annexe… verdict ?', NOW() - INTERVAL 2040 MINUTE),
(24,53,'Pour moi oui : un démarrage plus garni et du contenu réparti dans toute l’histoire.', NOW() - INTERVAL 2011 MINUTE),
(24,60,'Pour 20 $, ça reste raisonnable si tu joues beaucoup. Sinon la Standard fait le taf.', NOW() - INTERVAL 1982 MINUTE),
(24,85,'Les boutiques exclusives (Rideout Customs, Electric Fang Tattoo) me tentent pas mal pour le style.', NOW() - INTERVAL 1953 MINUTE),
(24,43,'Tant que c’est du contenu solo et pas un pay-to-win online, je valide.', NOW() - INTERVAL 1924 MINUTE),
(25,59,'Idée : on se retrouve tous ici le 19 novembre au soir, on partage nos premières impressions en direct !', NOW() - INTERVAL 1560 MINUTE),
(25,76,'OUI carrément, avec Vice FM en fond et le compte à rebours du site 📻', NOW() - INTERVAL 1531 MINUTE),
(25,31,'En stream je serai là, on réagira ensemble au lancement.', NOW() - INTERVAL 1502 MINUTE),
(25,98,'Présent ! Je ramène les memes pour patienter pendant l’installation 😂', NOW() - INTERVAL 1473 MINUTE),
(25,83,'Belle idée. Les soirées de lancement, c’est ça la magie d’une communauté.', NOW() - INTERVAL 1444 MINUTE),
(26,60,'Moi j’attends les avis et les patchs. Un jeu se bonifie après le lancement.', NOW() - INTERVAL 1080 MINUTE),
(26,59,'Team day-one sans hésiter ! Vivre le truc en même temps que tout le monde, ça n’a pas de prix.', NOW() - INTERVAL 1051 MINUTE),
(26,67,'Les deux camps ont raison, question de tempérament.', NOW() - INTERVAL 1022 MINUTE),
(26,43,'Patience aussi pour voir comment ils gèrent l’économie online avant de dépenser.', NOW() - INTERVAL 993 MINUTE),
(26,95,'Day-one les yeux fermés, c’est Rockstar 🤩', NOW() - INTERVAL 964 MINUTE),
(27,65,'Un mois de GTA+ offert en précommande numérique : GTA$ 500 000, Shark Cards +15 %, véhicules en rotation… vous allez en profiter ?', NOW() - INTERVAL 600 MINUTE),
(27,53,'Carrément, autant prendre le dépôt mensuel et la bibliothèque de jeux tant que c’est offert.', NOW() - INTERVAL 571 MINUTE),
(27,43,'Je reste prudent : tant que je sais pas comment l’online de GTA VI sera branché, je m’emballe pas.', NOW() - INTERVAL 542 MINUTE),
(27,16,'Les Shark Cards +15 %, ça peut être utile au lancement du online si tu veux gagner du temps.', NOW() - INTERVAL 513 MINUTE),
(27,99,'Je comprends à moitié 😅 mais ça a l’air d’un bon bonus pour débuter, non ?', NOW() - INTERVAL 484 MINUTE);
