
-- ====== Forum GTA VI : 50 personas de plus + catégorie + sujets ======
INSERT INTO users (username, email, display_name, password_hash, role) VALUES
('precommande_dan','precommande_dan@fans.vicehubx.test','PrecommandeDan','!','member'),
('deal_hunter_d','deal_hunter_d@fans.vicehubx.test','DealHunterD','!','member'),
('ps5_pierre','ps5_pierre@fans.vicehubx.test','PS5Pierre','!','member'),
('xbox_xavier','xbox_xavier@fans.vicehubx.test','XboxXavier','!','member'),
('collector_maniac','collector_maniac@fans.vicehubx.test','CollectorManiac','!','member'),
('day_one_dia','day_one_dia@fans.vicehubx.test','DayOneDia','!','member'),
('patient_paul','patient_paul@fans.vicehubx.test','PatientPaul','!','member'),
('wallet_warrior','wallet_warrior@fans.vicehubx.test','WalletWarrior','!','member'),
('trailer_addict','trailer_addict@fans.vicehubx.test','TrailerAddict','!','member'),
('florida_man','florida_man@fans.vicehubx.test','FloridaMan','!','member'),
('coop_dreamer','coop_dreamer@fans.vicehubx.test','CoopDreamer','!','member'),
('online_oga','online_oga@fans.vicehubx.test','OnlineOga','!','member'),
('lore_lucie','lore_lucie@fans.vicehubx.test','LoreLucie','!','member'),
('skeptik_sam','skeptik_sam@fans.vicehubx.test','SkeptikSam','!','member'),
('modder_mika','modder_mika@fans.vicehubx.test','ModderMika','!','member'),
('casual_clo','casual_clo@fans.vicehubx.test','CasualClo','!','member'),
('tryhard_tom','tryhard_tom@fans.vicehubx.test','TryhardTom','!','member'),
('story_first','story_first@fans.vicehubx.test','StoryFirst','!','member'),
('radio_raph','radio_raph@fans.vicehubx.test','RadioRaph','!','member'),
('screenshot_sky','screenshot_sky@fans.vicehubx.test','ScreenshotSky','!','member'),
('econ_emma','econ_emma@fans.vicehubx.test','EconEmma','!','member'),
('nostalgia_ned','nostalgia_ned@fans.vicehubx.test','NostalgiaNed','!','member'),
('hype_helena','hype_helena@fans.vicehubx.test','HypeHelena','!','member'),
('quiet_quentin','quiet_quentin@fans.vicehubx.test','QuietQuentin','!','member'),
('tech_tina','tech_tina@fans.vicehubx.test','TechTina','!','member'),
('biker_bob','biker_bob@fans.vicehubx.test','BikerBob','!','member'),
('heist_hugo','heist_hugo@fans.vicehubx.test','HeistHugo','!','member'),
('flamingo_fan','flamingo_fan@fans.vicehubx.test','FlamingoFan','!','member'),
('soundtrack_su','soundtrack_su@fans.vicehubx.test','SoundtrackSu','!','member'),
('veteran_vic','veteran_vic@fans.vicehubx.test','VeteranVic','!','member'),
('meme_maya','meme_maya@fans.vicehubx.test','MemeMaya','!','member'),
('completionist_cy','completionist_cy@fans.vicehubx.test','CompletionistCy','!','member'),
('rp_roman','rp_roman@fans.vicehubx.test','RPRoman','!','member'),
('street_racer','street_racer@fans.vicehubx.test','StreetRacer','!','member'),
('storm_chaser_s','storm_chaser_s@fans.vicehubx.test','StormChaserS','!','member'),
('budget_collector','budget_collector@fans.vicehubx.test','BudgetCollector','!','member'),
('console_war_no','console_war_no@fans.vicehubx.test','ConsoleWarNo','!','member'),
('early_bird','early_bird@fans.vicehubx.test','EarlyBird','!','member'),
('lurker_leo','lurker_leo@fans.vicehubx.test','LurkerLeo','!','member'),
('fan_art_fay','fan_art_fay@fans.vicehubx.test','FanArtFay','!','member'),
('pessimist_pat','pessimist_pat@fans.vicehubx.test','PessimistPat','!','member'),
('optimist_oli','optimist_oli@fans.vicehubx.test','OptimistOli','!','member'),
('data_miner','data_miner@fans.vicehubx.test','DataMiner','!','member'),
('couch_coop','couch_coop@fans.vicehubx.test','CouchCoop','!','member'),
('night_owl_n','night_owl_n@fans.vicehubx.test','NightOwlN','!','member'),
('first_gta','first_gta@fans.vicehubx.test','FirstGTA','!','member'),
('veteran_vera','veteran_vera@fans.vicehubx.test','VeteranVera','!','member'),
('region_ana','region_ana@fans.vicehubx.test','RegionAna','!','member'),
('hardcore_h','hardcore_h@fans.vicehubx.test','HardcoreH','!','member'),
('chill_charles','chill_charles@fans.vicehubx.test','ChillCharles','!','member');

INSERT INTO forum_categories (id, name, slug, description, icon, sort) VALUES
(6, 'GTA VI', 'gta-vi', 'Précommandes, éditions, hype et compte à rebours : tout sur GTA VI.', '🎮', 5);

INSERT INTO forum_threads (id, category_id, user_id, title, slug, pinned, created_at, last_post_at) VALUES
(14,6,53,'🎉 LES PRÉCOMMANDES DE GTA VI SONT OUVERTES !!','les-pr-commandes-de-gta-vi-sont-ouvertes-3f6',1, NOW() - INTERVAL 114 HOUR, NOW() - INTERVAL 108 HOUR),
(15,6,4,'Quelle édition vous prenez ? Standard, Deluxe ou Collector ?','quelle-edition-vous-prenez-standard-deluxe-ou-collector-3f7',0, NOW() - INTERVAL 106 HOUR, NOW() - INTERVAL 101 HOUR),
(16,6,53,'J’ai précommandé le Collector, posez-moi vos questions 😎','j-ai-precommande-le-collector-posez-moi-vos-questions-3f8',0, NOW() - INTERVAL 98 HOUR, NOW() - INTERVAL 93 HOUR),
(17,6,55,'Précommande PS5 ou Xbox Series, vous faites quoi ?','precommande-ps5-ou-xbox-series-vous-faites-quoi-3f9',0, NOW() - INTERVAL 90 HOUR, NOW() - INTERVAL 85 HOUR),
(18,6,54,'Où précommander au meilleur prix ? (balancez vos bons plans)','ou-precommander-au-meilleur-prix-balancez-vos-bons-plans-3fa',0, NOW() - INTERVAL 82 HOUR, NOW() - INTERVAL 77 HOUR),
(19,6,67,'Faut-il vraiment précommander ? Le débat 🍿','faut-il-vraiment-precommander-le-debat-3fb',0, NOW() - INTERVAL 74 HOUR, NOW() - INTERVAL 69 HOUR),
(20,6,14,'J-XXX : c’est quoi VOTRE plan pour le jour de la sortie ?','j-xxx-c-est-quoi-votre-plan-pour-le-jour-de-la-sortie-3fc',0, NOW() - INTERVAL 66 HOUR, NOW() - INTERVAL 61 HOUR),
(21,6,53,'Les bonus de précommande, ça vaut le coup selon vous ?','les-bonus-de-precommande-ca-vaut-le-coup-selon-vous-3fd',0, NOW() - INTERVAL 58 HOUR, NOW() - INTERVAL 53 HOUR),
(22,6,21,'Première fois que je précommande un jeu… des conseils ?','premiere-fois-que-je-precommande-un-jeu-des-conseils-3fe',0, NOW() - INTERVAL 50 HOUR, NOW() - INTERVAL 45 HOUR),
(23,6,4,'Le Collector contiendrait quoi selon vous ? (vos rêves)','le-collector-contiendrait-quoi-selon-vous-vos-reves-3ff',0, NOW() - INTERVAL 42 HOUR, NOW() - INTERVAL 37 HOUR),
(24,6,59,'On se fait une soirée de lancement ViceHub X ? 🌴','on-se-fait-une-soiree-de-lancement-vicehub-x-400',0, NOW() - INTERVAL 34 HOUR, NOW() - INTERVAL 29 HOUR),
(25,6,60,'Team patience vs team day-one : qui a raison ? 😅','team-patience-vs-team-day-one-qui-a-raison-401',0, NOW() - INTERVAL 26 HOUR, NOW() - INTERVAL 21 HOUR),
(26,6,78,'Côté technique, vous attendez quoi de plus ? (RAGE, fps…)','cote-technique-vous-attendez-quoi-de-plus-rage-fps-402',0, NOW() - INTERVAL 18 HOUR, NOW() - INTERVAL 13 HOUR),
(27,6,99,'GTA VI sera mon tout premier GTA, je suis sur un nuage ☁️','gta-vi-sera-mon-tout-premier-gta-je-suis-sur-un-nuage-403',0, NOW() - INTERVAL 10 HOUR, NOW() - INTERVAL 5 HOUR);

INSERT INTO forum_posts (thread_id, user_id, body, created_at) VALUES
(14,53,'ÇA Y EST LES AMIS, les précommandes sont LÀ 😭🌴 j’ai pris le Collector direct, mon cœur n’a pas tenu une seconde !', NOW() - INTERVAL 6840 MINUTE),
(14,75,'Enfin… j’attends ça depuis 2002. Vice City qui revient, et maintenant je peux réserver. Je suis ému 🥲', NOW() - INTERVAL 6811 MINUTE),
(14,59,'Pareil DAY ONE confirmé, j’ai posé mon congé pour la sortie 😎', NOW() - INTERVAL 6782 MINUTE),
(14,9,'Direct vérifié la fiche, vivement de savoir ce qu’il y a dans le Collector côté goodies 🏎️', NOW() - INTERVAL 6753 MINUTE),
(14,98,'Précommande validée à la première minute, fier de mon numéro de commande 🔥', NOW() - INTERVAL 6724 MINUTE),
(14,10,'On se calme, lisez bien les conditions de remboursement avant de foncer 👀', NOW() - INTERVAL 6695 MINUTE),
(15,4,'Je suis tentée par le Collector mais le prix… vous partez sur quoi vous ?', NOW() - INTERVAL 6360 MINUTE),
(15,57,'Collector évidemment, je les prends toujours. Steelbook + statuette = bonheur.', NOW() - INTERVAL 6331 MINUTE),
(15,65,'Standard pour moi, je préfère mettre le budget dans le online plus tard.', NOW() - INTERVAL 6302 MINUTE),
(15,63,'Deluxe le bon compromis je pense : les bonus sans exploser le budget.', NOW() - INTERVAL 6273 MINUTE),
(15,92,'Je lis tout avant de décider, mais je penche Deluxe aussi.', NOW() - INTERVAL 6244 MINUTE),
(16,53,'Voilà c’est fait, AMA ! Je partage tout ce que je sais sur l’édition.', NOW() - INTERVAL 5880 MINUTE),
(16,88,'Le prix exact tu l’as eu où ? je compare les régions.', NOW() - INTERVAL 5851 MINUTE),
(16,53,'Sur la boutique officielle, mais vérifie chez les revendeurs aussi, parfois moins cher.', NOW() - INTERVAL 5822 MINUTE),
(16,43,'Tu crains pas les microtransactions derrière ? moi je reste prudent.', NOW() - INTERVAL 5793 MINUTE),
(16,94,'Même question, le Collector c’est bien mais j’espère pas un online blindé de boutique.', NOW() - INTERVAL 5764 MINUTE),
(17,55,'Team PlayStation ici, hâte de sentir le DualSense sur la conduite 🎮', NOW() - INTERVAL 5400 MINUTE),
(17,56,'Xbox Series X pour moi, et si ça arrive un jour sur Game Pass je signe direct.', NOW() - INTERVAL 5371 MINUTE),
(17,89,'Vous allez pas recommencer la console-war 😅 prenez ce que vous avez, le jeu sera ouf partout.', NOW() - INTERVAL 5342 MINUTE),
(17,16,'Côté perf je croise les doigts pour un 60fps stable, peu importe la machine.', NOW() - INTERVAL 5313 MINUTE),
(17,17,'Team PC qui attend dans le silence… patience, notre heure viendra 🕯️', NOW() - INTERVAL 5284 MINUTE),
(18,54,'Je compare tout depuis ce matin. Certains revendeurs cassent déjà les prix.', NOW() - INTERVAL 4920 MINUTE),
(18,88,'Pense aux versions régionales, mais attention aux restrictions d’activation.', NOW() - INTERVAL 4891 MINUTE),
(18,100,'Je traque les codes promo, je vous tiens au courant si je trouve mieux.', NOW() - INTERVAL 4862 MINUTE),
(18,60,'Perso j’attends une petite baisse, rien ne presse, la sortie est pas demain.', NOW() - INTERVAL 4833 MINUTE),
(18,53,'Le Collector part vite par contre, si vous le voulez, tardez pas trop 👀', NOW() - INTERVAL 4804 MINUTE),
(19,67,'Honnêtement, précommander un jeu pas sorti, c’est risqué non ? « wait and see ».', NOW() - INTERVAL 4440 MINUTE),
(19,60,'D’accord à 100%. J’attends les retours, surtout sur l’optimisation.', NOW() - INTERVAL 4411 MINUTE),
(19,53,'Mais pour le Collector, si tu précommandes pas, tu l’auras jamais 😭', NOW() - INTERVAL 4382 MINUTE),
(19,95,'C’est Rockstar, ils nous ont jamais déçus sur la qualité. Je fonce, confiance totale.', NOW() - INTERVAL 4353 MINUTE),
(19,43,'Confiance oui, mais vigilance sur la boutique online. On a déjà vu les dérives.', NOW() - INTERVAL 4324 MINUTE),
(20,14,'CONGÉ POSÉ. Frigo plein. Téléphone en avion. JE NE RÉPONDS À PERSONNE 😤🌴', NOW() - INTERVAL 3960 MINUTE),
(20,59,'Soirée de lancement avec les potes, on lance tous en même temps à minuit.', NOW() - INTERVAL 3931 MINUTE),
(20,69,'Moi je vais juste me balader tranquille la première heure, profiter de la ville 🌅', NOW() - INTERVAL 3902 MINUTE),
(20,21,'Mon tout premier GTA day one, je sais même pas par quoi commencer haha.', NOW() - INTERVAL 3873 MINUTE),
(20,102,'Conseil de vétéran : savoure l’intro, te précipite pas. Vice City se mérite.', NOW() - INTERVAL 3844 MINUTE),
(21,53,'Cash in-game, tenues exclusives… vous pensez quoi des bonus annoncés ?', NOW() - INTERVAL 3480 MINUTE),
(21,74,'Le cash de départ peut aider à lancer l’économie, mais faut pas que ça déséquilibre.', NOW() - INTERVAL 3451 MINUTE),
(21,85,'Moi tant que c’est cosmétique je valide, l’important c’est le 100% du jeu de base.', NOW() - INTERVAL 3422 MINUTE),
(21,65,'Tant que c’est pas pay-to-win en online, ça me va.', NOW() - INTERVAL 3393 MINUTE),
(21,62,'Je résume pour ceux qui suivent : rien d’officiel à 100% encore, prudence sur les listes.', NOW() - INTERVAL 3364 MINUTE),
(22,21,'Je débute, GTA VI sera mon premier GTA ET ma première précommande. Aidez-moi 🙏', NOW() - INTERVAL 3000 MINUTE),
(22,60,'Garde ta preuve d’achat, vérifie la date de débit et la politique de remboursement.', NOW() - INTERVAL 2971 MINUTE),
(22,53,'Et choisis bien ta plateforme, c’est le plus important. Bienvenue dans la hype 😄', NOW() - INTERVAL 2942 MINUTE),
(22,76,'BIENVENUE 🌴✨ tu vas A-DO-RER, prépare-toi à ne plus dormir.', NOW() - INTERVAL 2913 MINUTE),
(22,92,'Pose toutes tes questions ici, la communauté est top pour ça.', NOW() - INTERVAL 2884 MINUTE),
(23,4,'Statuette de Lucia & Jason, steelbook, carte de Leonida en tissu… je rêve déjà.', NOW() - INTERVAL 2520 MINUTE),
(23,93,'Un art book avec les concepts arts, ce serait le pied pour les fans 🎨', NOW() - INTERVAL 2491 MINUTE),
(23,57,'Une vraie cassette audio collector avec des morceaux des radios, là je meurs.', NOW() - INTERVAL 2462 MINUTE),
(23,81,'Un petit flamant rose néon à poser sur le bureau et je signe à vie 🦩.', NOW() - INTERVAL 2433 MINUTE),
(23,53,'Vos idées sont géniales, j’espère que Rockstar lit ce forum 😂', NOW() - INTERVAL 2404 MINUTE),
(24,59,'Idée : on se retrouve tous ici le soir de la sortie, on partage nos premières impressions en direct !', NOW() - INTERVAL 2040 MINUTE),
(24,76,'OUI carrément, avec Vice FM en fond et le compte à rebours du site 📻', NOW() - INTERVAL 2011 MINUTE),
(24,31,'En stream je serai là, on pourra réagir ensemble au lancement.', NOW() - INTERVAL 1982 MINUTE),
(24,98,'Présent ! Je ramène les memes pour patienter pendant l’installation 😂', NOW() - INTERVAL 1953 MINUTE),
(24,83,'Belle idée. Les soirées de lancement, c’est ça la magie d’une communauté.', NOW() - INTERVAL 1924 MINUTE),
(25,60,'Moi j’attends les patchs et les avis. Un jeu se bonifie après le lancement.', NOW() - INTERVAL 1560 MINUTE),
(25,59,'Team day-one sans hésiter ! Vivre le truc en même temps que tout le monde, ça n’a pas de prix.', NOW() - INTERVAL 1531 MINUTE),
(25,67,'Les deux camps ont raison en vrai, question de tempérament.', NOW() - INTERVAL 1502 MINUTE),
(25,43,'Patience aussi pour voir comment ils gèrent l’économie online avant de dépenser.', NOW() - INTERVAL 1473 MINUTE),
(25,95,'Day-one les yeux fermés, c’est Rockstar 🤩', NOW() - INTERVAL 1444 MINUTE),
(26,78,'Moi c’est le moteur RAGE qui m’obsède : eau, météo, foule réactive. Le bond doit être énorme.', NOW() - INTERVAL 1080 MINUTE),
(26,96,'Je vais data-miner le moindre détail dès que possible 👀 la tech me passionne.', NOW() - INTERVAL 1051 MINUTE),
(26,16,'Surtout un framerate stable. 60fps console et je suis comblé.', NOW() - INTERVAL 1022 MINUTE),
(26,33,'Les détails des PNJ et la physique, c’est là que se joue l’immersion pour moi.', NOW() - INTERVAL 993 MINUTE),
(26,17,'Et sur PC, le ray tracing… le jour où ça sort, préparez vos cartes graphiques.', NOW() - INTERVAL 964 MINUTE),
(27,99,'Jamais touché un GTA de ma vie, et là je précommande le premier. Je flippe un peu et j’ai trop hâte.', NOW() - INTERVAL 600 MINUTE),
(27,102,'Tu vas vivre un grand moment. Prends ton temps, explore, parle aux gens dans le jeu.', NOW() - INTERVAL 571 MINUTE),
(27,69,'Pas de pression, GTA c’est aussi le plaisir de juste se balader. Profite 🌴', NOW() - INTERVAL 542 MINUTE),
(27,76,'BIENVENUE dans la famille 🥹 on est tous passés par un premier GTA un jour.', NOW() - INTERVAL 513 MINUTE),
(27,53,'Et viens nous raconter tes premières impressions ici, on adore ça !', NOW() - INTERVAL 484 MINUTE);
